name: club
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.7.0
  firebase_core: ^3.15.2
  random_string: ^2.3.1
  firebase_storage: ^12.4.10
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  get: ^4.6.5
  image_picker: ^1.1.2
  proste_bezier_curve: ^2.0.2
  file_picker: ^10.1.9
  showcaseview: ^4.0.1
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4
  pin_code_fields: ^8.0.1
  flutter_easyloading: ^3.0.5
  google_sign_in: ^6.2.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  image_cropper:
  mime: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_slider_drawer: ^3.0.2
  pdf: ^3.10.4
  permission_handler: ^12.0.0+1
  path_provider: ^2.0.13
  share_plus: ^11.0.0
  url_launcher: ^6.1.10
  url_launcher_ios: ^6.3.2
  cloudflare: ^5.0.0
  file: ^7.0.1
  flutter_barcode_scanner:
    git:
      url: https://github.com/decodevM/flutter_barcode_scanner.git
      ref: flutter-3.29
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_database: ^11.1.4
  firebase_dynamic_links: ^6.0.8
  intl: ^0.20.2
  fl_chart: ^0.69.0
  flutter_facebook_auth:
  firebase_ui_oauth_facebook:
  syncfusion_flutter_pdfviewer: ^29.2.5
  csv:
  phyllo_connect: ^0.3.3
  http: ^1.2.2
  loading_indicator: ^3.1.1
  country_codes: ^3.1.0+2
  #  pod_player: 0.2.2
  uuid: ^4.5.1
  multi_dropdown: ^3.0.1
  flutter_phosphor_icons: ^0.0.1+6
  flutter_file_downloader: ^2.0.0
  qr_flutter: ^4.1.0
  flutter_secure_storage: any
  dio: ^5.7.0
  dotted_line: ^3.2.3
  bouncing_widget: ^2.0.0
  razorpay_flutter: ^1.3.4
  open_filex: ^4.3.2
  pretty_qr_code: ^3.1.0
  printing: ^5.11.0
  blue_thermal_printer: ^1.2.3
  pie_chart: ^5.4.0
  number_to_words_english: ^2.1.1
  video_player: ^2.9.0
  smooth_page_indicator: any
  sendotp_flutter_sdk: ^0.0.1
  msg91: ^1.0.5




dependency_overrides:
  firebase_auth_web:
  firebase_storage_web:
  image_cropper_for_web:
  image_cropper_platform_interface: ^6.0.0
  flutter_barcode_scanner:
    git:
      url: https://github.com/decodevM/flutter_barcode_scanner
      ref: flutter-3.29 # This parameter is responsible for which branch to use

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  shared_preferences: ^2.3.3


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/playstoreIcon.png"
  adaptive_icon_background: "#171716"

flutter_native_splash:
  color: "#000000"
  image: assets/newLogo.png

  android_12:
    image: assets/newLogo.png
    color: "#171716"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.jpg
    - assets/newLogo.png
    - assets/gold_heading.png
    - assets/featEvent.png
    - assets/
    - assets/video/
    - assets/video/venue/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
