// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmMaAorHzDKkYbOJOtli3Tvz4c877NRRY',
    appId: '1:835379344984:android:ca2c9843fb950070eb7c2d',
    messagingSenderId: '835379344984',
    projectId: 'partyon-artist-demo',
    databaseURL: 'https://partyon-artist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'partyon-artist-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmMaAorHzDKkYbOJOtli3Tvz4c877NRRY',
    appId: '1:835379344984:android:ca2c9843fb950070eb7c2d',
    messagingSenderId: '835379344984',
    projectId: 'partyon-artist-demo',
    storageBucket: 'partyon-artist-demo.firebasestorage.app',
    androidClientId:
        '835379344984-c9odga949ans597qsdocnmonn160mtpf.apps.googleusercontent.com',
    // iosClientId:
    //     '774845460870-uv8avvp2fb5qdpv83k7rk0b2dos3265o.apps.googleusercontent.com',
    iosBundleId: 'hashtag.partyonDemo.partner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmMaAorHzDKkYbOJOtli3Tvz4c877NRRY',
    appId: '1:835379344984:android:ca2c9843fb950070eb7c2d',
    messagingSenderId: '835379344984',
    projectId: 'partyon-artist-demo',
    storageBucket: 'partyon-artist-demo.firebasestorage.app',
    authDomain: 'partyon-artist.firebaseapp.com',
    databaseURL: 'https://partyon-artist-default-rtdb.asia-southeast1.firebasedatabase.app',
    measurementId: 'G-6B9LWTGQH6',
  );

}